#!/usr/bin/env python3
"""Generate embedded web content header file"""

def file_to_header(file_path, var_name):
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    # Use raw string literal to avoid escaping issues
    return f'const char {var_name}[] = R"=====(\n{content}\n)=====";\n\n'

# Generate header file
with open('src/web_content.h', 'w', encoding='utf-8') as out:
    out.write("// Auto-generated web content - DO NOT EDIT MANUALLY\n")
    out.write("// Generated by generate_web_content.py\n\n")
    out.write("#ifndef WEB_CONTENT_H\n")
    out.write("#define WEB_CONTENT_H\n\n")
    
    out.write(file_to_header('data/lights.html', 'LIGHTS_HTML'))
    out.write(file_to_header('data/lights.css', 'LIGHTS_CSS'))
    out.write(file_to_header('data/lights.js', 'LIGHTS_JS'))
    
    out.write("#endif // WEB_CONTENT_H\n")

print("Generated src/web_content.h successfully")
